# name of the software
name: Prebid.js
# current version of the software
version: 1.0.0
# url of the download button
downloadUrl: https://github.com/prebid/Prebid.js/releases
# licence of the software
license: Apache License
licenseUrl: http://www.apache.org/licenses/LICENSE-2.0

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/prebid/Prebid.js


# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/prebid/Prebid.js
  - title: Issues
    url: https://github.com/prebid/Prebid.js/issues?state=open
  - title: About Us
    url: /about.html


# header
header:
  #color1: "#0084B4"
  #color1: "#55acee"
  color1: "#3b88c3"
  #color1: "#2ABBB0"
  
  #color1: "#080331"
  #color2: "#673051"
  trianglify: false

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: prebid
  repo: Prebid.js

# twitter buttons
twitter:
  enabled: true
  via:
  hash: prebidjs
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# Build settings
markdown: kramdown

nav_sections:
  - top_nav: dev_docs
    code: quick-start
    name: QUICK START
  - top_nav: dev_docs
    code: troubleshooting
    name: TROUBLESHOOTING
  - top_nav: dev_docs
    code: reference
    name: REFERENCE
  - top_nav: dev_docs
    code: adaptors
    name: ADAPTORS

  - top_nav: overview
    code: intro
    name: INTRO
  - top_nav: overview
    code: analytics
    name: ANALYTICS
  - top_nav: overview
    code: studies
    name: LATEST STUDIES


  - top_nav: adops
    code: tutorials
    name: TUTORIALS

  - top_nav: support
    code: support
    name: SUPPORT


port: 80

exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
