# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/Prebid.js

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo npm install -g gulp-cli
      # Download and run BrowserStack local
      - run:
          name : Download BrowserStack Local binary and start it.
          command : |
            # Download the browserstack binary file
            wget "https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip"
            # Unzip it
            unzip BrowserStackLocal-linux-x64.zip
            # Run the file with user's access key
            ./BrowserStackLocal ${BROWSERSTACK_ACCESS_KEY} &
      # run tests!
      - run: 
          name: BrowserStack testing
          command: gulp test --browserstack --nolintfix
