# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

aliases:
  - &environment
    docker:
      # specify the version you desire here
      - image: circleci/node:12.16.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    working_directory: ~/Prebid.js

  - &restore_dep_cache
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-

  - &save_dep_cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package.json" }}

  - &install
    name: Install gulp cli
    command: sudo npm install -g gulp-cli

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.12
jobs:
  build:
    <<: *environment
    steps:
      - checkout
      - run: echo "export UPLOAD_DEST='s3://embedproduction/files/instbid-$(git describe --tags).js'" >> "$BASH_ENV"
      - restore_cache: *restore_dep_cache
      - run: npm install
      - save_cache: *save_dep_cache
      - run: *install
      - run:
          name: Build Prebid.js
          command: gulp build --modules=modules.json
      - aws-s3/copy:
          from: build/dist/prebid.js
          to: '"$UPLOAD_DEST"'
          arguments: --cache-control 'max-age=86400'

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-aws
          filters:
            branches:
              only: master
