name: Run unit tests
on:
  workflow_call:
    inputs:
      source-key:
        description: Artifact name for source directory
        type: string
        required: false
        default: source
      build-cmd:
        description: Build command
        required: false
        type: string
      run-npm-install:
        description: Run npm install
        type: boolean
        required: false
        default: false
    outputs:
      built-key:
        description: Artifact name for built directory
        value: ${{ jobs.build.outputs.built-key }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      built-key: ${{ (inputs.build-cmd || inputs.run-npm-install) && format('build-{0}', steps.build-id.outputs.id) || inputs.source-key }}
    steps:
      - name: Checkout
        if: ${{ inputs.build-cmd || inputs.run-npm-install }}
        uses: actions/checkout@v5
      - name: Restore source
        if: ${{ inputs.build-cmd || inputs.run-npm-install }}
        uses: ./.github/actions/load
        with:
          name: ${{ inputs.source-key }}
      - name: Run npm install
        if: ${{ inputs.run-npm-install }}
        run: npm install
      - name: Build
        if: ${{ inputs.build-cmd }}
        run: ${{ inputs.build-cmd }}
      - name: Generate build ID
        id: build-id
        if: ${{ inputs.build-cmd || inputs.run-npm-install }}
        run:
          echo 'id='"$(uuidgen)" >> "$GITHUB_OUTPUT";
      - name: 'Save working directory'
        if: ${{ inputs.build-cmd  || inputs.run-npm-install }}
        uses: ./.github/actions/save
        with:
          name: build-${{ steps.build-id.outputs.id }}
