name: Build and publish
on: 
  pull_request:
  push: 
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: â¬‡ Checkout
      uses: actions/checkout@v2

    - name: Configure access
      run: |
        git config --local user.email 'tech@marfeel.com'
        git config --local user.name 'GitHub Action'

    - name: ğŸ”§ Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@marfeel'

    - name: ğŸ“¦ Install
      uses: Marfeel/github-actions/common/actions/initialize@master
      with:
        gh-token: ${{ secrets.BOB_GITHUB_TOKEN }}

    - name: ğŸ›  Build
      run: gulp build --modules=modules.json

    - name: â— Create prebid.ww.js from prebid.js
      run: cp /build/dist/prebid.js /build/dist/prebid.ww.js 

    - name: â™»ï¸ Adapt to web worker
      run: sed -i 's/location/originalLocation/g' ./build/dist/prebid.ww.js

    - name: ğŸš€ Publish
      run: npm publish 

