name: Run unit tests
on:
  workflow_call:
    inputs:
      build-cmd:
        description: Build command, run once
        required: true
        type: string
      test-cmd:
        description: Test command, run once per chunk
        required: true
        type: string
      serialize:
        description: If true, allow only one concurrent chunk (see note on concurrency below)
        required: false
        type: boolean
    outputs:
      wdir:
        description: Cache key for the working directory after running tests
        value: ${{ jobs.chunk-8.outputs.wdir }}
    secrets:
      BROWSERSTACK_USER_NAME:
        description: "Browserstack user name"
      BROWSERSTACK_ACCESS_KEY:
        description: "Browserstack access key"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Fetch source
        uses: actions/cache/restore@v4
        with:
          path: .
          key: source-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Build
        run: ${{ inputs.build-cmd }}

      - name: Save working directory
        uses: ./.github/actions/cache
        with:
          key: build-${{ inputs.build-cmd }}-${{ github.run_id }}

  run-tests:
    needs: build
    uses: ./.github/workflows/test-chunks.yml
    with:
      chunks: 8
      wdir: build-${{ inputs.build-cmd }}-${{ github.run_id }}
      cmd: ${{ inputs.test-cmd }}
      serialize: ${{ inputs.serialize }}
