name: Run unit tests
on:
  workflow_call:
    inputs:
      chunks:
        description: Number of chunks to split tests into
        required: true
        type: number
      build-cmd:
        description: Build command, run once
        required: true
        type: string
      test-cmd:
        description: Test command, run once per chunk
        required: true
        type: string
      browserstack:
        description: If true, set up browserstack environment and adjust concurrency
        required: false
        type: boolean
    outputs:
      coverage:
        description: Cache key for coverage results
        value: ${{ jobs.collect-coverage.outputs.coverage }}
    secrets:
      BROWSERSTACK_USER_NAME:
        description: "Browserstack user name"
      BROWSERSTACK_ACCESS_KEY:
        description: "Browserstack access key"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      chunks: ${{ steps.chunks.outputs.chunks }}
      wdir: build-${{ inputs.build-cmd }}-${{ github.run_id }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Fetch source
        uses: actions/cache/restore@v4
        with:
          path: .
          key: source-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Build
        run: ${{ inputs.build-cmd }}

      - name: Save working directory
        uses: ./.github/actions/cache
        with:
          key: build-${{ inputs.build-cmd }}-${{ github.run_id }}

      - name: Define chunks
        id: chunks
        run: |
          echo 'chunks=[ '$(seq --separator=, 1 1 ${{ inputs.chunks }})' ]' >> "$GITHUB_OUTPUT"
          

  run-tests:
    needs: build
    strategy:
      fail-fast: false
      max-parallel: ${{ inputs.browserstack && 1 || inputs.chunks }}
      matrix:
        chunk-no: ${{ fromJSON(needs.build.outputs.chunks) }}

    name: "Test chunk ${{ matrix.chunk-no }}"
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      TEST_CHUNKS: ${{ inputs.chunks }}
      TEST_CHUNK: ${{ matrix.chunk-no }}
    outputs:
      coverage: ${{ steps.coverage.outputs.coverage }}
      coverage-id: test-${{ inputs.cmd }}-${{ matrix.chunk-no }}-${{ github.run_id }}
    concurrency:
      # The following generates 'browserstack-<run_id>' when inputs.browserstack is true, and a hopefully unique ID otherwise
      # Ideally we'd like to serialize browserstack access across all workflows, but github's max queue length is only 1
      # (cfr. https://github.com/orgs/community/discussions/12835)
      # so we add the run_id to serialize only within one push / pull request (which has the effect of queueing e2e and unit tests)
      group: ${{ inputs.browserstack && 'browser' || github.run_id }}${{ inputs.browserstack && 'stac' || inputs.test-cmd }}${{ inputs.browserstack && 'k' || matrix.chunk-no }}-${{ github.run_id }}
      cancel-in-progress: false

    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Restore working directory
        id: restore-dir
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ needs.build.outputs.wdir }}
          fail-on-cache-miss: true

      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USER_NAME}}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'BrowserStackLocal Setup'
        if: ${{ inputs.browserstack }}
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: start
          local-identifier: random

      - name: 'Wait for browserstack'
        if: ${{ inputs.browserstack }}
        uses: ./.github/actions/wait-for-browserstack
        with:
          BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Run tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 8
          max_attempts: 3
          command: ${{ inputs.test-cmd }}

      - name: 'BrowserStackLocal Stop'
        if: ${{ inputs.browserstack }}
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: stop

      - name: 'Check for coverage'
        id: 'coverage'
        run: |
          if [ -d "./build/coverage" ]; then 
            echo 'coverage=true' >> "$GITHUB_OUTPUT";
          fi

      - name: 'Save coverage result'
        if: ${{ steps.coverage.outputs.coverage }}
        uses: ./.github/actions/cache
        with:
          key: test-${{ inputs.test-cmd }}-${{ matrix.chunk-no }}-${{ github.run_id }}
          path: './build/coverage'

  collect-coverage:
    if: ${{ needs.run-tests.outputs.coverage }}
    needs: [build, run-tests]
    name: 'Collect coverage results'
    runs-on: ubuntu-latest
    outputs:
      coverage: ${{ steps.set-coverage.outputs.key }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
      - name: Restore working directory
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ needs.build.outputs.wdir }}
          fail-on-cache-miss: true
      - run: |
          npm install @actions/cache
          mkdir ${{ runner.temp }}/coverage
      - uses: actions/github-script@v8
        with:
          script: |
            const cache = require('@actions/cache');
            const chunks = ${{ needs.build.outputs.chunks }};
            const os = require('os');
            const path = require('path');
            const process = require('process');
            const fs = require('node:fs/promises');
            
            const src = './build/coverage';
            const dest = path.join('${{ runner.temp }}', 'coverage');
            
            for (const chunk of chunks) {
              if (
                await cache.restoreCache(
                    ['build/coverage'],
                    'test-${{ inputs.test-cmd }}-' + chunk + '-${{ github.run_id }}'
                ) == null
              ) {
                 console.error('Coverage result not found for chunk' + chunk);
                 process.exit(1);
              } else {
                await fs.cp(src, dest, {recursive: true});
                await fs.rm(src, {recursive: true, force: true});
              }
            }
      - id: set-coverage
        run: |
          find coverage
          rm -r build
          mv ${{runner.temp}}/coverage .
          echo 'key=coverage-${{ inputs.test-cmd }}-${{ github.run_id }}' >> "$GITHUB_OUTPUT"

      - name: Save coverage results
        uses: ./.github/actions/cache
        with:
          path: ./coverage
          key: ${{ steps.set-coverage.outputs.key }}

