name: Run unit tests
on:
  workflow_call:
    inputs:
      chunks:
        description: Number of chunks to split tests into
        required: true
        type: number
      build-cmd:
        description: Build command, run once
        required: true
        type: string
      test-cmd:
        description: Test command, run once per chunk
        required: true
        type: string
      serialize:
        description: If true, allow only one concurrent chunk (see note on concurrency below)
        required: false
        type: boolean
    outputs:
      wdir:
        description: Cache key for the working directory after running tests
        value: 'temp'
    secrets:
      BROWSERSTACK_USER_NAME:
        description: "Browserstack user name"
      BROWSERSTACK_ACCESS_KEY:
        description: "Browserstack access key"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      chunks: ${{ steps.chunks.outputs.chunks }}
      wdir: build-${{ inputs.build-cmd }}-${{ github.run_id }}
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Fetch source
        uses: actions/cache/restore@v4
        with:
          path: .
          key: source-${{ github.run_id }}
          fail-on-cache-miss: true

      - name: Build
        run: ${{ inputs.build-cmd }}

      - name: Save working directory
        uses: ./.github/actions/cache
        with:
          key: build-${{ inputs.build-cmd }}-${{ github.run_id }}

      - name: Define chunks
        id: chunks
        run: |
          echo 'chunks=[ '$(seq --separator=, 1 1 ${{ inputs.chunks }})' ]' >> "$GITHUB_OUTPUT"
        

  run-tests:
    needs: build
    strategy:
      matrix:
        chunk-no: ${{ fromJSON(needs.build.outputs.chunks) }}
    name: "Test chunk ${{ matrix.chunk }}"
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      TEST_CHUNKS: ${{ inputs.chunks }}
      TEST_CHUNK: ${{ matrix.chunk-no }}
    outputs:
      coverage: test-${{ inputs.cmd }}-${{ matrix.chunk-no }}-${{ github.run_id }}
    concurrency:
      # The following generates 'browserstack-<run_id>' when inputs.serialize is true, and a hopefully unique ID otherwise
      # Ideally we'd like to serialize browserstack access across all workflows, but github's max queue length is only 1
      # (cfr. https://github.com/orgs/community/discussions/12835)
      # so we add the run_id to serialize only within one push / pull request (which has the effect of queueing e2e and unit tests)
      group: ${{ inputs.serialize && 'browser' || github.run_id }}${{ inputs.serialize && 'stack' || inputs.test-cmd }}${{ inputs.serialize && '' || matrix.chunk-no }}-${{ github.run_id }}
      cancel-in-progress: false

    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Restore working directory
        id: restore-dir
        uses: actions/cache/restore@v4
        with:
          path: .
          key: ${{ needs.build.outputs.wdir }}
          fail-on-cache-miss: true

      - name: 'BrowserStack Env Setup'
        uses: 'browserstack/github-actions/setup-env@master'
        with:
          username:  ${{ secrets.BROWSERSTACK_USER_NAME}}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: 'BrowserStackLocal Setup'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: start
          local-identifier: random

      - name: 'Wait for browserstack'
        if: ${{ inputs.serialize }}
        uses: ./.github/actions/wait-for-browserstack
        with:
          BROWSERSTACK_USER_NAME: ${{ secrets.BROWSERSTACK_USER_NAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: Run tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 8
          max_attempts: 3
          command: ${{ inputs.test-cmd }}

      - name: 'BrowserStackLocal Stop'
        uses: 'browserstack/github-actions/setup-local@master'
        with:
          local-testing: stop

      - name: 'Save coverage result'
        uses: ./.github/actions/cache
        with:
          key: test-${{ inputs.cmd }}-${{ matrix.chunk-no }}-${{ github.run_id }}
          path: './build/coverage'
